# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-06-28 18:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20200628_1757'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='registration_status',
            field=models.CharField(choices=[('Not Closed', 'Not Closed'), ('Closed', 'Closed')], default='Not Closed', max_length=20),
        ),
    ]
